-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  sleep_start time not null default '23:00',
  sleep_end time not null default '07:00'
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create events table
create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text not null default 'pending', -- 'pending', 'completed', 'skipped'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.events enable row level security;

-- Create messages table (for community chat)
create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- nullable if we allow anon chat, but better with auth
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies (Simple for now, can be restricted later)
-- Allow users to view their own profile/events
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

create policy "Users can view own events" on public.events for select using (auth.uid() = user_id);
create policy "Users can insert own events" on public.events for insert with check (auth.uid() = user_id);
create policy "Users can update own events" on public.events for update using (auth.uid() = user_id);

-- Allow everyone to view/insert messages (public chat)
create policy "Anyone can view messages" on public.messages for select using (true);
create policy "Authenticated users can insert messages" on public.messages for insert with check (auth.role() = 'authenticated');
